In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from xgboost import XGBClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, f1_score, recall_score, confusion_matrix, classification_report

In [2]:
#by doing test1.ipynb
#best model is xgboost with 0.97  accuracy and 0.96 recall {'learning_rate': 0.1, 'max_depth': 5, 'n_estimators': 300}
#2nd best model is decision tree with 0.96 accuracy and 0.95 recall {'criterion': 'entropy', 'max_depth': 7, 'min_samples_split': 5}

In [3]:
ohe = OneHotEncoder()

cat_cols = ['category','gender', 'day', 'distance_km']

preprocessor = ColumnTransformer(
    [('one_hot_encoder', ohe, cat_cols)], remainder = 'passthrough'
)

In [4]:
def compare_models_on_different_data(df):
    x = df.drop('is_fraud', axis=1)
    y = df['is_fraud']

    x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

    x_train = preprocessor.fit_transform(x_train)
    x_test = preprocessor.transform(x_test)

    dt = DecisionTreeClassifier(criterion= 'entropy', max_depth= 7, min_samples_split= 5)
    xgb = XGBClassifier(learning_rate = 0.1, max_depth= 5, n_estimators = 300)

    models = [
        ('Decision Tree', dt),
        ('XGBoost', xgb)
    ]

    for name, model in models:
        model.fit(x_train, y_train)
        y_pred = model.predict(x_test)
        accuracy = accuracy_score(y_test, y_pred)
        f1 = f1_score(y_test, y_pred)
        recall = recall_score(y_test, y_pred)
        print(f"{name} Accuracy: {accuracy:.2f}")
        print(f"{name} F1 Score: {f1:.2f}")
        print(f"{name} Recall: {recall:.2f}")
        print(f"{name} Confusion Matrix:\n {confusion_matrix(y_test, y_pred)}")
        print(f"{name} Classification Report:\n {classification_report(y_test, y_pred)}")

In [5]:
df = pd.read_csv('data2.csv')
compare_models_on_different_data(df)

Decision Tree Accuracy: 0.96
Decision Tree F1 Score: 0.96
Decision Tree Recall: 0.95
Decision Tree Confusion Matrix:
 [[1871   58]
 [ 103 1829]]
Decision Tree Classification Report:
               precision    recall  f1-score   support

           0       0.95      0.97      0.96      1929
           1       0.97      0.95      0.96      1932

    accuracy                           0.96      3861
   macro avg       0.96      0.96      0.96      3861
weighted avg       0.96      0.96      0.96      3861

XGBoost Accuracy: 0.97
XGBoost F1 Score: 0.97
XGBoost Recall: 0.97
XGBoost Confusion Matrix:
 [[1867   62]
 [  51 1881]]
XGBoost Classification Report:
               precision    recall  f1-score   support

           0       0.97      0.97      0.97      1929
           1       0.97      0.97      0.97      1932

    accuracy                           0.97      3861
   macro avg       0.97      0.97      0.97      3861
weighted avg       0.97      0.97      0.97      3861



In [6]:
df = pd.read_csv('data3.csv')
compare_models_on_different_data(df)

Decision Tree Accuracy: 0.96
Decision Tree F1 Score: 0.96
Decision Tree Recall: 0.95
Decision Tree Confusion Matrix:
 [[1886   43]
 [ 104 1828]]
Decision Tree Classification Report:
               precision    recall  f1-score   support

           0       0.95      0.98      0.96      1929
           1       0.98      0.95      0.96      1932

    accuracy                           0.96      3861
   macro avg       0.96      0.96      0.96      3861
weighted avg       0.96      0.96      0.96      3861

XGBoost Accuracy: 0.97
XGBoost F1 Score: 0.97
XGBoost Recall: 0.97
XGBoost Confusion Matrix:
 [[1882   47]
 [  52 1880]]
XGBoost Classification Report:
               precision    recall  f1-score   support

           0       0.97      0.98      0.97      1929
           1       0.98      0.97      0.97      1932

    accuracy                           0.97      3861
   macro avg       0.97      0.97      0.97      3861
weighted avg       0.97      0.97      0.97      3861



In [7]:
df = pd.read_csv('data4.csv')
compare_models_on_different_data(df)

Decision Tree Accuracy: 0.96
Decision Tree F1 Score: 0.96
Decision Tree Recall: 0.95
Decision Tree Confusion Matrix:
 [[1873   56]
 [  95 1837]]
Decision Tree Classification Report:
               precision    recall  f1-score   support

           0       0.95      0.97      0.96      1929
           1       0.97      0.95      0.96      1932

    accuracy                           0.96      3861
   macro avg       0.96      0.96      0.96      3861
weighted avg       0.96      0.96      0.96      3861

XGBoost Accuracy: 0.97
XGBoost F1 Score: 0.97
XGBoost Recall: 0.97
XGBoost Confusion Matrix:
 [[1877   52]
 [  49 1883]]
XGBoost Classification Report:
               precision    recall  f1-score   support

           0       0.97      0.97      0.97      1929
           1       0.97      0.97      0.97      1932

    accuracy                           0.97      3861
   macro avg       0.97      0.97      0.97      3861
weighted avg       0.97      0.97      0.97      3861



In [8]:
df = pd.read_csv('data5.csv')
compare_models_on_different_data(df)

Decision Tree Accuracy: 0.96
Decision Tree F1 Score: 0.96
Decision Tree Recall: 0.95
Decision Tree Confusion Matrix:
 [[1890   39]
 [  97 1835]]
Decision Tree Classification Report:
               precision    recall  f1-score   support

           0       0.95      0.98      0.97      1929
           1       0.98      0.95      0.96      1932

    accuracy                           0.96      3861
   macro avg       0.97      0.96      0.96      3861
weighted avg       0.97      0.96      0.96      3861

XGBoost Accuracy: 0.97
XGBoost F1 Score: 0.97
XGBoost Recall: 0.97
XGBoost Confusion Matrix:
 [[1879   50]
 [  58 1874]]
XGBoost Classification Report:
               precision    recall  f1-score   support

           0       0.97      0.97      0.97      1929
           1       0.97      0.97      0.97      1932

    accuracy                           0.97      3861
   macro avg       0.97      0.97      0.97      3861
weighted avg       0.97      0.97      0.97      3861



In [9]:
df = pd.read_csv('data6.csv')
compare_models_on_different_data(df)

Decision Tree Accuracy: 0.96
Decision Tree F1 Score: 0.96
Decision Tree Recall: 0.95
Decision Tree Confusion Matrix:
 [[1880   49]
 [  97 1835]]
Decision Tree Classification Report:
               precision    recall  f1-score   support

           0       0.95      0.97      0.96      1929
           1       0.97      0.95      0.96      1932

    accuracy                           0.96      3861
   macro avg       0.96      0.96      0.96      3861
weighted avg       0.96      0.96      0.96      3861

XGBoost Accuracy: 0.97
XGBoost F1 Score: 0.97
XGBoost Recall: 0.97
XGBoost Confusion Matrix:
 [[1880   49]
 [  53 1879]]
XGBoost Classification Report:
               precision    recall  f1-score   support

           0       0.97      0.97      0.97      1929
           1       0.97      0.97      0.97      1932

    accuracy                           0.97      3861
   macro avg       0.97      0.97      0.97      3861
weighted avg       0.97      0.97      0.97      3861



In [10]:
df = pd.read_csv('data7.csv')
compare_models_on_different_data(df)

Decision Tree Accuracy: 0.96
Decision Tree F1 Score: 0.96
Decision Tree Recall: 0.94
Decision Tree Confusion Matrix:
 [[1875   54]
 [ 110 1822]]
Decision Tree Classification Report:
               precision    recall  f1-score   support

           0       0.94      0.97      0.96      1929
           1       0.97      0.94      0.96      1932

    accuracy                           0.96      3861
   macro avg       0.96      0.96      0.96      3861
weighted avg       0.96      0.96      0.96      3861

XGBoost Accuracy: 0.97
XGBoost F1 Score: 0.97
XGBoost Recall: 0.97
XGBoost Confusion Matrix:
 [[1865   64]
 [  56 1876]]
XGBoost Classification Report:
               precision    recall  f1-score   support

           0       0.97      0.97      0.97      1929
           1       0.97      0.97      0.97      1932

    accuracy                           0.97      3861
   macro avg       0.97      0.97      0.97      3861
weighted avg       0.97      0.97      0.97      3861



In [11]:
#best model accros all data is xgboost with 0.97  accuracy and 0.96 recall {'learning_rate': 0.1, 'max_depth': 5, 'n_estimators': 300}